# Generated by Django 5.1 on 2024-08-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_pizzeria_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='logo_image',
            field=models.ImageField(blank=True, default='pizzariImages/pizza_image2.png', upload_to='pizzariaImages'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos')),
                ('image_title', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pizzeria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzeria_images', to='stores.pizzeria')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
